### PR TITLE
Fix build parameters

### LINKED ISSUE #443: Allow passing parameters to build.sh and build.ps1 script
The `build.sh` and `build.ps1` scripts don't support passing parameters. This is unfortunate as we then cannot run a single exercise in the build. 

To fix this, we should look at how Cake defines their default shell script themselves: https://github.com/cake-build/resources/blob/develop/build.sh
https://github.com/cake-build/resources/blob/develop/build.ps1

### LINKED ISSUE #444: Build scripts should also install .NET Core 1.0.4 runtime

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR updates the build loader script to better comply to the default Cake build loader scripts. In the process, I've fixes two issues:

Fixes #443: easier passing of single exercise argument
Fixes #444: install .NET Core 1.0.4 runtime

### CODE REVIEW

**Comment by jpreese** [comment]
Looks like @felix91gr's commit snuck into this one.

**Comment by felix91gr** [comment]
Uh oh, that shouldn’t be happenning I don’t think. Since Erik’s been helping me, he must’ve left one of my commits unintentionally in his branch.

File: generators/Exercises/DifferenceOfSquares.cs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+using Generators.Input;
+using System;
+
+namespace Generators.Exercises
+{
+    public class DifferenceOfSquares : Exercise
+    {        
+    }
+}
```
Comment (jpreese) [inline generators/Exercises/DifferenceOfSquares.cs]: Someone wasn't invited to the party

**Comment by ErikSchierboom** [comment]
@jpreese Whoops, my bad! I've updated the PR.

**Comment by jpreese** [comment]
Awesomesauce, thanks! 🎉
