### PR TITLE
generators: fix sgf-parsing generator

### LINKED ISSUE #749: Fix sfg-parsing example to pass with the latest test data
There's one new example that fails.

To repro:
- go to the generators folder
- run `dotnet run -e sfg-parsing`
- go to the root folder
- run `./build.sh --exercise=sfg-parsing` or `.\build.ps1 -Exercise sfg-parsing`

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes #749

### CODE REVIEW

File: exercises/sgf-parsing/SgfParsingTest.cs [hunk 1]
```diff
@@ -31,7 +31,7 @@ public void Node_without_tree()
     public void Node_without_properties()
     {
         var encoded = "(;)";
-        var expected = new SgfTree(new Dictionary<string, string[]>());
+        var expected = new SgfTree(new Dictionary<string, string[]>() );
```
Comment (robkeim) [inline exercises/sgf-parsing/SgfParsingTest.cs]: Super minor but do you know why the generator is generating these extra spaces here (they're in the rest of the file as well).

Comment (ErikSchierboom) [reply exercises/sgf-parsing/SgfParsingTest.cs]: I found the issue. PR has been updated.

And I appreciate this minor nits by the way :)

**Comment by robkeim** [comment]
Thanks @ErikSchierboom! 👍
